// utils/funnyNames.js

export const funnyNames = [
  "Captain Carbon",
  "EcoNinja",
  "Watt-a-Planet",
  "Footprint Phantom",
  "Sir Emission-a-Lot",
  "Green Goblin",
  "Carbonator",
  "Solar Squirrel",
  "Leafy McLeafface",
  "Recycle Rex",
  "Wind Warrior",
  "Eco Avenger",
  "Gas Masked Hero",
  "Tree Hugger",
  "Compost Commander",
  "Power Plant Pete",
  "Planet Protector",
  "Eco Explorer",
  "Watt Wonder",
  "Carbon Crusader",
  "Smog Slayer",
  "Green Machine",
  "Lightbulb Larry",
  "Emission Enforcer",
  "Veggie Vindicator",
  "Eco Enigma",
  "Solar Sam",
  "Hydrogen Hero",
  "Carbon King",
  "Leaf Lifter",
  "Eco Elf",
  "Green Giant",
  "Watts Up",
  "Footprint Fighter",
  "Eco Eagle",
  "Carbon Cat",
  "Tree Titan",
  "Renewable Randy",
  "Power Saver",
  "Captain Compost",
  "Leaf Ninja",
  "Green Gobbler",
  "Watt Wizard",
  "Planet Paladin",
  "Emission Emperor",
  "Solar Sorcerer",
  "Gas Guru",
  "Eco Engineer",
  "Leaf Legend",
  "Carbon Cowboy",
  "Eco Otter",
  "Watt Warrior",
  "Tree Trapper",
  "Green Gremlin",
  "Photon Phantom",
  "Emission Elf",
  "Solar Samurai",
  "Carbon Commander",
  "Leaf Lord",
  "Planet Panther",
  "Eco Emperor",
  "Watt Warden",
  "Renewable Robin",
  "Gas Guardian",
  "Tree Tamer",
  "Eco Elephant",
  "Carbon Crusader",
  "Leaf Leopard",
  "Solar Sprite",
  "Eco Enforcer",
  "Watt Wolf",
  "Planet Pixie",
  "Tree Troll",
  "Green Goblin Jr.",
  "Carbon Cougar",
  "Eco Eagle Eye",
  "Leaf Lynx",
  "Solar Shark",
  "Watt Wizardry",
  "Emission Eagle",
  "Captain Compost Jr.",
  "Leaf Llama",
  "Green Gecko",
  "Photon Phantom Jr.",
  "Gas Gopher",
  "Eco Emu",
  "Carbon Cheetah",
  "Watt Walrus",
  "Tree Toucan",
  "Solar Sparrow",
  "Eco Eskimo",
  "Leaf Lizard",
  "Carbon Kangaroo",
  "Planet Platypus",
  "Watt Wombat",
  "Tree Tiger",
  "Eco Eel",
  "Solar Seal",
  "Carbon Cobra",
  "Leaf Lynx Jr.",
];

export const getRandomName = () => {
  return funnyNames[Math.floor(Math.random() * funnyNames.length)];
};
